apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app-deployment
  labels:
    app: dummy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: index.docker.io/yaroslavkostyannikov/node-dummy-app
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-app-service
spec:
  ports:
  - nodePort: 31001
    targetPort: 3000
    port: 3000
    protocol: TCP
  selector:
    app: dummy-app
  type: NodePort

